org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=26.2
loader_version=0.19.5
loom_version=1.17-SNAPSHOT
fabric_version=0.155.2+26.2
java_version=25
gradle_java_version=25

mod_version=2.2.1-web.6
maven_group=com.yourname.simpletranslate
archives_base_name=simple_translate

mod_id=simple_translate
mod_name=Simple Translate Web
mod_license=MIT
mod_authors=baokaixing
mod_description=Fast keyless Google translation for chat, items, books, signs, HUD and Wynncraft dialogues. Based on SimpleTranslate by baokaixina.







modmenu_modrinth_version=3gAjUrx6
